class Basket:
    CHECKOUT_BTN = "[data-test='checkout']"
    FIRST_NAME = "[data-test='firstName']"
    LAST_NAME = "[data-test='lastName']"
    ZIP = "[data-test='postalCode']"
    CNT_BTN = "[data-test='continue']"
    FINISH_BTN = "[data-test='finish']"
    FINAL_TEXT = "//span[text()='Checkout: Complete!']"
    CART_ITEM = "[data-test='inventory-item']"
    REMOVED_CART_ITEM = "[class='removed_cart_item']"
    CART_LIST = "[data-test='cart-list']"